### ISSUE TITLE
Unable to submit files

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#102]
Trying to submit 400+ files.

Internal Server Error: /submit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 105, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/csrf.py", line 170, in process_view
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 146, in _get_post
    self._load_post_and_files()
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 215, in _load_post_and_files
  File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 180, in parse_file_upload
  File "/usr/local/lib/python2.7/dist-packages/django/http/multipartparser.py", line 197, in parse
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/uploadhandler.py", line 135, in new_file
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/uploadedfile.py", line 63, in __init__
  File "/usr/lib/python2.7/tempfile.py", line 462, in NamedTemporaryFile
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/tmp/tmpgQhdOq.upload'

**Comment by KillerInstinct** [comment]
I believe this is the internals of Django, and not something we can natively handle. When a file gets passed to our code, we write it to whatever your temp path is configured to and to a directory upload_[random]/ -- it looks like you're running out of file descriptors before we even hit that code.

One question I have -- Are you front-ending the Django app with any web server like Apache/nginx? or just using manage.py to run the dev server?

As for a way to make this work, I would suggest one of three things:
1) Use utils/submit.py to submit the directory
2) Increase the amount of file descriptors you can have open (usually /etc/security/limits.conf, i think sysctl can do this too)
3) Use the API and submit them programatically one by one.

**Comment by brad-sp** [comment]
If the webserver is still running when this error occurs, could you pastebin me a listing of /proc/[pid of the python django instance]/fd ?  I'd like to see what files are involved.

**Comment by ghost** [comment]
I'm so sorry, already restarted the machine.

Will just use the submit.py to submit the directory instead using web upload (if files are morethan 300+)
Thanks for the help
