### ISSUE TITLE
Analysis failed: invalid string pointer 0x034F1E1000000000

### ISSUE THREAD

**Issue by ernestszocs** [brad-accuvant/cuckoo-modified#116]
Hi,
When I try to submit the sample with submit.py I get this error: "Analysis failed: invalid string pointer 0x034F1E1000000000" in cuckoo.py. Does anyone know what's the issue? Thanks.

**Comment by KillerInstinct** [comment]
Do you have the full traceback?

**Comment by ernestszocs** [comment]
Here is the full traceback:
2015-07-23 15:31:14,328 [root] INFO: Date set to: 03-25-15, time set to: 15:31:1
2
2015-07-23 15:31:14,328 [root] ERROR: Traceback (most recent call last):
  File "C:\ltgdpnkjj\analyzer.py", line 930, in <module>
    success = analyzer.run()
  File "C:\ltgdpnkjj\analyzer.py", line 663, in run
    self.prepare()
  File "C:\ltgdpnkjj\analyzer.py", line 603, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\ltgdpnkjj\analyzer.py", line 552, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.Uniqu
eProcessId))
ValueError: invalid string pointer 0x034F1E1000000000
Traceback (most recent call last):
  File "C:\ltgdpnkjj\analyzer.py", line 930, in <module>
    success = analyzer.run()
  File "C:\ltgdpnkjj\analyzer.py", line 663, in run
    self.prepare()
  File "C:\ltgdpnkjj\analyzer.py", line 603, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\ltgdpnkjj\analyzer.py", line 552, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.Uniqu
eProcessId))
ValueError: invalid string pointer 0x034F1E1000000000

**Comment by brad-sp** [comment]
This is from using a 64-bit version of python in the guest.  Only 32-bit versions of Python are currently supported, but you'll still be able to analyze 64-bit binaries with it.

**Comment by SteveClement** [comment]
@brad-accuvant Do you know of any impacts when the underlying Arch is 64bit? (I hit the same issue on 7 and 8.1)

**Comment by KillerInstinct** [comment]
There shouldn't be any, as long as you use 32-bit python. I've tested on W7 x86/x64 and XP x86.
