### ISSUE TITLE
After update: Cuckoo is not processing files correctly

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#134]
"Error loading data. Please reload the page and if the error persists contact us."

SHA1    441e9a76239722e7b7dee89a0b8b915e244e9c41

**Comment by ghost** [comment]
....
2015-04-06 17:08:14,983 [root] INFO: Added new process to list with pid: 1932
2015-04-06 17:08:15,062 [root] ERROR: Traceback (most recent call last):
  File "C:\humrw\analyzer.py", line 341, in run
    elif commands.startswith("SHUTDOWN:"):
NameError: global name 'commands' is not defined
Traceback (most recent call last):
  File "C:\humrw\analyzer.py", line 341, in run
    elif commands.startswith("SHUTDOWN:"):
NameError: global name 'commands' is not defined
....

Seems fixed now after recent update
just sytax error
