### ISSUE TITLE
reporting module MongoDB fails on multiple samples

### ISSUE THREAD

**Issue by 05hi** [brad-accuvant/cuckoo-modified#14]
On sample 74bef950220b1385ae539016e85c1852 and multiple others I get the following error:

2015-03-16 17:58:50,519 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "JsonDump"
2015-03-16 17:58:55,459 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/plugins.py", line 570, in process
    current.run(self.results)
  File "/home/cuckoo/cuckoo-modified/modules/reporting/mongodb.py", line 259, in run
    self.db.analysis.save(report)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 266, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 362, in insert
    self.database.connection)
InvalidStringData: strings in documents must be valid UTF-8: 'G8\x94g\x89\x04VCr\x89EvG8IXd7\x84g'
2015-03-16 17:59:05,721 [lib.cuckoo.core.plugins] DEBUG: Executed reporting module "ReportHTML"

**Comment by brad-sp** [comment]
Hi, that should be fixed now via this commit: https://github.com/brad-accuvant/cuckoo-modified/commit/0be51049b1a6663963d445c06486395871491250

Thanks for the report!

**Comment by 05hi** [comment]
Hi, yeah, works well now. Thanks! for the fix and all the great work
