### ISSUE TITLE
Error accessing analysis

### ISSUE THREAD

**Issue by therealdreg** [brad-accuvant/cuckoo-modified#154]
Hi Brad, I have the last master version and I have this error when I access to analysis:

Internal Server Error: /analysis/1/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", li                                                                                        ne 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py",                                                                                         line 45, in inner
    return func(request, _args, *_kwargs)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 426, in report
    if not report:
UnboundLocalError: local variable 'report' referenced before assignment
[18/Aug/2015 08:21:01]"GET /analysis/1/ HTTP/1.1" 500 73334
Internal Server Error: /analysis/1/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", li                                                                                        ne 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py",                                                                                         line 45, in inner
    return func(request, _args, *_kwargs)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 426, in report
    if not report:
UnboundLocalError: local variable 'report' referenced before assignment
[18/Aug/2015 08:21:39]"GET /analysis/1/ HTTP/1.1" 500 73628

And when I access to recent:

[18/Aug/2015 08:21:39]"GET /analysis/1/ HTTP/1.1" 500 73628
[18/Aug/2015 08:24:21]"GET /analysis/pending/ HTTP/1.1" 200 3151
[18/Aug/2015 08:24:23]"GET /analysis/search/ HTTP/1.1" 200 8958
[18/Aug/2015 08:24:23]"GET /api/ HTTP/1.1" 200 20985
[18/Aug/2015 08:24:25]"GET /submit/ HTTP/1.1" 200 15284
[18/Aug/2015 08:24:26]"GET /dashboard/ HTTP/1.1" 200 4672
Internal Server Error: /analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, _args, *_kwargs)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 158, in index
    new = get_analysis_info(db, task=task)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 97, in get_analysis_info
    if rtmp:
UnboundLocalError: local variable 'rtmp' referenced before assignment
[18/Aug/2015 08:24:28]"GET /analysis/ HTTP/1.1" 500 81389
Internal Server Error: /analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, _args, *_kwargs)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 158, in index
    new = get_analysis_info(db, task=task)
  File "/home/cuckoo/cuckoo-modified/web/analysis/views.py", line 97, in get_analysis_info
    if rtmp:
UnboundLocalError: local variable 'rtmp' referenced before assignment
[18/Aug/2015 08:24:34]"GET /analysis/ HTTP/1.1" 500 81389

**Comment by KillerInstinct** [comment]
ElasticSearch or MongoDB?

**Comment by therealdreg** [comment]
MongoDB

**Comment by KillerInstinct** [comment]
Able to share your reporting config options for MongoDB? I don't see how report or rtmp could be undefined, considering the first thing we do after checking if MongoDB is enabled, is define those variables in their respective functions.

https://github.com/brad-accuvant/cuckoo-modified/blob/master/web/analysis/views.py#L412

https://github.com/brad-accuvant/cuckoo-modified/blob/master/web/analysis/views.py#L75

Also, what version of Pymongo? Those calls should return a cursor object, or None.

**Comment by therealdreg** [comment]
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
fix_large_docs = yes

**Comment by KillerInstinct** [comment]
What version on Pymongo?

**Comment by therealdreg** [comment]
pymongo==3.0.2

**Comment by KillerInstinct** [comment]
Can you try the following? Am curious if there's a version issue.

```
pip uninstall pymongo
pip install pymongo==2.7.2
```

**Comment by therealdreg** [comment]
I have the same error with this version :\

**Comment by KillerInstinct** [comment]
Okay, think I found it. This should be a version issue. Pymongo deprecated collection.save() past 3.x it seems. For the moment, downgrade to 2.x and then reprocess your analysis.

Source:
http://api.mongodb.org/python/current/api/pymongo/collection.html?highlight=save#pymongo.collection.Collection.save

**Comment by KillerInstinct** [comment]
Make sure you reprocess your analysis with process.py -r 1

The issue lies in the saving on the analysis, not accessing it with Django. :)

**Comment by therealdreg** [comment]
same error

**Comment by therealdreg** [comment]
Here the debug info via web:

http://pastebin.com/y8rTAiQa

**Comment by KillerInstinct** [comment]
Can you drop this python script in your $CUCKOO_ROOT and run it, if it errors out, can you manually run the commented out code in whatever shell you're using?

https://gist.github.com/KillerInstinct/32ed6c55201b39e93500

**Comment by therealdreg** [comment]
cuckoo@luciewilde:~/cuckoo-modified$ python dbtest.py
4

cuckoo@luciewilde:~/cuckoo-modified$ mongo cuckoo
MongoDB shell version: 2.0.6
connecting to: cuckoo

> show collections
> analysis
> calls
> cuckoo_schema
> fs.chunks
> fs.files
> system.indexes
> db.analysis.count()
> 4

**Comment by therealdreg** [comment]
I try remove and create mongo database, mysql database and re-do analysis and I have the same error

use cuckoo;
db.dropDatabase();

..

**Comment by therealdreg** [comment]
I re-do all the installation and now works fine :\, sorry for the waste of time. Thx four your active support!
