### ISSUE TITLE
Analyzer.py errors

### ISSUE THREAD

**Issue by KillerInstinct** [brad-accuvant/cuckoo-modified#177]
Not sure what the actual impact of these are. :)

```
2015-08-28 06:32:16,358 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 3452
2015-08-28 06:32:16,934 [root] INFO: Disabling sleep skipping.
2015-08-28 06:32:17,029 [root] INFO: Added new process to list with pid: 3452
2015-08-28 06:32:17,029 [root] INFO: Cuckoomon successfully loaded in process with pid 3452.
2015-08-28 06:32:17,855 [root] ERROR: Traceback (most recent call last):
  File "C:\hjtfpslm\analyzer.py", line 313, in run
    si.dwFlags = subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
Traceback (most recent call last):
  File "C:\hjtfpslm\analyzer.py", line 313, in run
    si.dwFlags = subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
```

**Comment by KillerInstinct** [comment]
Appears to be a Guest Python Version issue. Need something > 2.7.0 to resolve this.
