### ISSUE TITLE
memory_dump enabled, but memory dump isn't created

### ISSUE THREAD

**Issue by rprasko** [brad-accuvant/cuckoo-modified#180]
To all,

I am trying to attach Volatility to my AC Cuckoo Sandbox. I have downloaded and installed Volatility 2.3.1 and it's dependencies, have enabled memory_dump in cuckoo.conf, and have enabled memory in processing.conf but still get the following error in terminal.

2015-08-31 13:14:08,616 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label accuckoo_w7 to path /home/sandbox/accuckoo/storage/analyses/21/memory.dmp
2015-08-31 13:14:13,720 [modules.processing.memory] ERROR: Memory dump not found: to run volatility you have to enable memory_dump

Although it says successfully created I cannot find memory.dmp in the file path mentioned above. The following is from

processing.conf:
[memory]
enabled = yes

cuckoo.conf
Enable creation of memory dump of the analysis machine before shutting
down. Even if turned off, this functionality can also be enabled at
submission. Currently available for: VirtualBox and libvirt modules (KVM).

memory_dump = on

Anything is appreciated, hopefully this is just dependency issues but hope you can help

Thanks

**Comment by brad-sp** [comment]
Is it the latest version of VirtualBox?  There was a recent change to support the latest version: https://github.com/brad-accuvant/cuckoo-modified/commit/7bf7d788450147a181e4863a3c7cd2ebf448c1e2

Does reverting that change fix the issue?

**Comment by rprasko** [comment]
I currently have Virtualbox version 5.0.2. I looked into the link that you
provided in the response, and in my modules/machinery/virtualbox.py I do
not have the if/else that determines version number. It says that the
verison I have of the sandbox is up to date. Any other way that I should
update the files so that I can get this latest patch for Virtualbox 5.0.2?

Thanks,
    Ryan

**Comment by rprasko** [comment]
Hi,

I updated the modules and other config files for cuckoo modified and it gives me an AdderSpaceError. Added with other errors, but most resolve to No base Address Space. Here is the output I got during Memory Dump generation.

2015-09-09 13:33:23,259 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/sandbox/accuckoo/modules/processing/memory.py", line 1121, in run
    results = vol.run(manager=machine_manager, vm=task_machine)
  File "/home/sandbox/accuckoo/modules/processing/memory.py", line 1004, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/home/sandbox/accuckoo/modules/processing/memory.py", line 51, in **init**
    self.__config()
  File "/home/sandbox/accuckoo/modules/processing/memory.py", line 104, in __config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found

Volatility is version 2.4
VirtualBox is version 5.0.2
Cuckoo is version 1.3-Optiv

Anything will help.

Thanks,
     Ryan

**Comment by brad-sp** [comment]
What do you have mem_profile set to in your config entry for that VM in virtualbox.conf?  What's the guest OS?

**Comment by rprasko** [comment]
Since I have the sandbox running on Windows 7 SP 1 I have mem_profile Win7SP1x64 as of now, it did create a memory dump this time but man errors saying something about the profile could not be used. I'm going to try running the XPSP2x86 just to try it out. I'll let you know my results.

**Comment by rprasko** [comment]
The WinXPSP2x86 will not work correctly with mem_profile set to that config. Returning to Win7SP1x64, just getting errors such as the following: 

2015-09-09 14:11:36,962 [volatility.obj] WARNING: NoneObject as string: Cannot find process session

2015-09-09 14:12:50,877 [volatility.plugins.malware.idt] ERROR: This command does not support the selected profile.

2015-09-09 14:15:59,016 [volatility.plugins.malware.malfind] ERROR: Cannot compile rules: line 40: invalid regular expression in string "$buf": \k is not followed by a braced, angle-bracketed, or quoted name

2015-09-09 14:15:59,017 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory":

I realize this is more so on the Volatility end now and the memory dump created from Cuckoo trying to create a report for the web interface. I have Evolve which is a Web Interface for the Volatility Framework which I'm able to view the memory dump created. The dump is just not able to be viewed in the Cuckoo Sanbox Web Interface.

Thanks

**Comment by brad-sp** [comment]
With our memory.py, that idt error should be ignored as far as the processing module goes.  The malfind error is some problem in the rules you added.  Once that's fixed you'll be able to view the results in the web interface fine.
