### ISSUE TITLE
Web.py Import Error: No module named exceptions

### ISSUE THREAD

**Issue by hexlax** [brad-accuvant/cuckoo-modified#196]
Hello, I got the submit.py working perfectly, but when browsing the web interface for the first time I receive the following error:

```
$ python manage.py runserver 127.0.0.1:8123
Performing system checks...

System check identified no issues (0 silenced).
September 12, 2015 - 12:09:37
Django version 1.8.4, using settings 'web.settings'
Starting development server at http://127.0.0.1:8123/
Quit the server with CONTROL-C.
/Library/Python/2.7/site-packages/ratelimit/middleware.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Library/Python/2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
    mw_class = import_string(middleware_path)
  File "/Library/Python/2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/ratelimit/middleware.py", line 4, in <module>
    from ratelimit.exceptions import Ratelimited
ImportError: No module named exceptions
```

I googled around a bit to no avail. Do I have the wrong ratelimit package installed?

**Comment by KillerInstinct** [comment]
Yeah.

```
pip uninstall ratelimit
pip install django-ratelimit
```

**Comment by hexlax** [comment]
That was it, thanks! I removed both then added back django-ratelimit. Running great now, thanks again! Time to smash some samples!

**Comment by ghost** [comment]
Can you figure out the error on my setup?

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in **call**
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 170, in **call**
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 50, in load_middleware
    mw_class = import_string(middleware_path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/ratelimit/middleware.py", line 4, in <module>
    from ratelimit.exceptions import Ratelimited
ImportError: No module named exceptions

INFO:

> pip list | grep ratelimit
> django-ratelimit (0.5.0)
> ratelimit (0.0.1)
