### ISSUE TITLE
Tor issue

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#199]
I followed everything from here https://github.com/seanthegeek/routetor but when I run it I get this in the traceback at start :
Traceback (most recent call last):
  File "/usr/sbin/torstart", line 26, in <module>
    s.connect("/tmp/routetor")
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
2015-09-15 22:14:09,175 [modules.auxiliary.tor] INFO: Started Tor transparent proxy for 172.16.50.53

and at finish :
Traceback (most recent call last):
  File "/usr/sbin/torstop", line 26, in <module>
    s.connect("/tmp/routetor")
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
2015-09-15 22:16:32,875 [modules.auxiliary.tor] INFO: Shutdown Tor transparent proxy for 172.16.50.53

What is going wrong here ?

Thanks

**Comment by brad-sp** [comment]
Did you start /usr/sbin/routetor as root?

**Comment by dforce** [comment]
I placed it in  the crontab and then rebooted.
Noticed that the socket was created in /tmp.

**Comment by dforce** [comment]
Problem is solved.
When I start the routetor manually then there is no traceback.
I will remove it from the crontab and start it manually after rebooting.

**Comment by dforce** [comment]
How can I check if tor is really running ?

**Comment by b3nw** [comment]
try ps aux | grep tor

**Comment by dforce** [comment]
ok - thanks
