### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by b3nw** [brad-accuvant/cuckoo-modified#200]
after pulling e4dc6e9ef97093c6834bb59bf9f3f49d0f986c16 getting this error on start...

```
2015-09-16 23:24:19,471 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
Traceback (most recent call last):
  File "cuckoo.py", line 105, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 79, in cuckoo_main
    sched.start()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 548, in start
    self.initialize()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 516, in initialize
    machinery.initialize(machinery_name)
  File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 93, in initialize
    self._initialize(module_name)
  File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 152, in _initialize
    log.warning("Configuration details about machine %s are missing: %s", machine.id, e)
UnboundLocalError: local variable 'machine' referenced before assignment
```

**Comment by KillerInstinct** [comment]
I believe this error is from https://github.com/brad-accuvant/cuckoo-modified/commit/70cb5654d6bcd7413bb8f4d5c3fada78675333ff#diff-b554a7c7f40d9d04680eef90f59deac2

Can you change line 152 from

```
log.warning("Configuration details about machine %s are missing: %s", machine.id, e)
```

to

```
log.warning("Configuration details about machine %s are missing: %s", machine_id.strip(), e) 
```

I think that will fix it.

**Comment by b3nw** [comment]
no joy

```
2015-09-16 23:45:44,382 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
Traceback (most recent call last):
  File "cuckoo.py", line 105, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "cuckoo.py", line 79, in cuckoo_main
    sched.start()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 548, in start
    self.initialize()
  File "/opt/cuckoo/lib/cuckoo/core/scheduler.py", line 516, in initialize
    machinery.initialize(machinery_name)
  File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 93, in initialize
    self._initialize(module_name)
  File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 152, in _initialize
    log.warning("Configuration details about machine %s are missing: %s", machine.id.strip(), e)
UnboundLocalError: local variable 'machine' referenced before assignment

**Comment by b3nw** [comment]
that did fix it, thanks!
