### ISSUE TITLE
ImportError: No module named exceptions

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#207]
Can you figure out the error on my setup?

Traceback (most recent call last):
File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
self.result = application(self.environ, self.start_response)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in call
return self.application(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 170, in call
self.load_middleware()
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 50, in load_middleware
mw_class = import_string(middleware_path)
File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 26, in import_string
module = import_module(module_path)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/usr/local/lib/python2.7/dist-packages/ratelimit/middleware.py", line 4, in 
from ratelimit.exceptions import Ratelimited
ImportError: No module named exceptions

INFO:

> pip list | grep ratelimit
> django-ratelimit (0.5.0)
> ratelimit (0.0.1)

similar case to #196

**Comment by ghost** [comment]
Already did what @KillerInstinct said on the previous bug...

<code>pip uninstall ratelimit </br>
pip install django-ratelimit</code>

**Comment by KillerInstinct** [comment]
If you're still showing ratelimit (0.0.1) then it's not uninstalled.

```
pip uninstall ratelimit
pip uninstall django-ratelimit
pip install django-ratelimit
```

Should make it fresh again.

**Comment by ghost** [comment]
Thank you @KillerInstinct the web is now working fine. 

> django-ratelimit (0.6.0)
