### ISSUE TITLE
WSGI no longer runs correctly

### ISSUE THREAD

**Issue by geudrik** [brad-accuvant/cuckoo-modified#210]
From the commits, it appears that no significant changes were made that should impact WSGI functionality, but post pull yesterday, WSGI is refusing to load correctly (having been working quite well for the better part of a two weeks). No apache config changes were made prior to the 500's rolling out.

```
[Wed Sep 23 06:00:07.757396 2015] [:error] [pid 18347] [client 10.69.100.24:49605] mod_wsgi (pid=18347): Exception occurred processing WSGI script '/opt/cuckoo/cuckoo-modified/web/web/wsgi.py'.
[Wed Sep 23 06:00:07.757427 2015] [:error] [pid 18347] [client 10.69.100.24:49605] Traceback (most recent call last):
[Wed Sep 23 06:00:07.757451 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/opt/cuckoo/cuckoo-modified/web/web/wsgi.py", line 28, in <module>
[Wed Sep 23 06:00:07.757522 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     application = get_wsgi_application()
[Wed Sep 23 06:00:07.757543 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Wed Sep 23 06:00:07.757590 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     django.setup()
[Wed Sep 23 06:00:07.757610 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
[Wed Sep 23 06:00:07.757653 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Sep 23 06:00:07.757670 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
[Wed Sep 23 06:00:07.757753 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     self._setup(name)
[Wed Sep 23 06:00:07.757769 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
[Wed Sep 23 06:00:07.757788 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     self._wrapped = Settings(settings_module)
[Wed Sep 23 06:00:07.757799 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
[Wed Sep 23 06:00:07.757814 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Sep 23 06:00:07.757845 2015] [:error] [pid 18347] [client 10.69.100.24:49605]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Wed Sep 23 06:00:07.757915 2015] [:error] [pid 18347] [client 10.69.100.24:49605]     __import__(name)
[Wed Sep 23 06:00:07.757938 2015] [:error] [pid 18347] [client 10.69.100.24:49605] ImportError: No module named web.settings
```

Perms appear to be fine (apache processes run as my user)

```
root@host:/opt/cuckoo/cuckoo-modified/web/web# ll
total 72
drwxrwxr-x  2 plitke plitke 4096 Sep 23 05:40 ./
drwxrwxr-x 10 plitke plitke 4096 Sep  3 14:27 ../
-rw-rw-r--  1 plitke plitke  837 Sep  3 11:37 headers.py
-rw-r--r--  1 plitke plitke 1121 Sep  3 17:17 headers.pyc
-rwxrwxr-x  1 plitke plitke  167 Sep  3 11:37 __init__.py*
-rw-r--r--  1 plitke plitke  134 Sep  3 17:17 __init__.pyc
-rw-rw-r--  1 plitke plitke 1299 Sep  3 11:37 local_settings.py
-rw-r--r--  1 plitke plitke  381 Sep  3 17:17 local_settings.pyc
-rw-rw-r--  1 plitke plitke   65 Sep  3 14:24 secret_key.py
-rw-r--r--  1 plitke plitke  212 Sep  3 17:17 secret_key.pyc
-rwxrwxr-x  1 plitke plitke 6605 Sep  3 11:37 settings.py*
-rw-r--r--  1 plitke plitke 4972 Sep  3 17:17 settings.pyc
-rwxrwxr-x  1 plitke plitke  906 Sep  3 11:37 urls.py*
-rw-r--r--  1 plitke plitke  972 Sep  3 17:17 urls.pyc
-rwxrwxr-x  1 plitke plitke 1297 Sep 22 10:44 wsgi.py*
-rw-rw-r--  1 plitke plitke 1022 Sep 23 05:40 wsgi.pyc
root@host:/opt/cuckoo/cuckoo-modified/web/web# vim 
```

Testing interface works just fine

```
plitke@host:/opt/cuckoo/cuckoo-modified/web$ ./manage.py runserver 0.0.0.0:8123
Performing system checks...

System check identified no issues (0 silenced).
September 23, 2015 - 05:40:27
Django version 1.8.4, using settings 'web.settings'
Starting development server at http://0.0.0.0:8123/
Quit the server with CONTROL-C.

[23/Sep/2015 05:48:58] "GET / HTTP/1.1" 500 232473
[23/Sep/2015 05:49:23] "GET / HTTP/1.1" 200 4673
[23/Sep/2015 05:49:24] "GET /static/css/style.css HTTP/1.1" 200 3029
[23/Sep/2015 05:49:24] "GET /static/css/lightbox.css HTTP/1.1" 200 3744
...
```

**Comment by KillerInstinct** [comment]
In my experience:
ImportError: No module named web.settings

means that your sys paths aren't setup correctly.

1)
Make sure your webserver is executing in [path to cuckoo root]/web/
2)
You may need to add a:

```
sys.path.append([path to cuckoo root])
sys.path.append([path to cuckoo root]/web)
```

To your wsgi.py file if you're front ending it with apache.

**Comment by geudrik** [comment]
Yep, I remember this now. You also need to include 

```
os.chdir('[path to cuckoo]/web/')
```

with your additions.
