### ISSUE TITLE
Merge Android and Linux analyzers from upstream 

### ISSUE THREAD

**Issue by seanthegeek** [brad-accuvant/cuckoo-modified#214]
How much has the fork diverged? Would it be particularity difficult?

**Comment by brad-sp** [comment]
https://github.com/idanr1986/cuckoo-droid should be usable without any porting.  As for the Linux analyzer, I don't really like that it's simply using strace.  I'd like to have something with more thought/effort put into it.

**Comment by simonk9** [comment]
Brad, that is partially correct, i tried to add that to your cuckoo, i am having issues with the vm to run full cycle test, but there are errors for non-apk files:

> 2015-11-12 22:18:51,487 [lib.cuckoo.core.plugins] ERROR: Failed to load the processing module "class 'modules.processing.apkinfo.ApkInfo':
> Traceback (most recent call last):
>  File "/data/cuckoo/lib/cuckoo/core/plugins.py", line 162, in process
>     current = module(self.results)
> TypeError: **init**() takes exactly 1 argument (2 given)
> 
> 2015-11-12 22:18:51,990 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_kt9Oyk/98c46f1ee4f9dc5f" (task=656)
> 2015-11-12 22:18:52,374 [lib.cuckoo.core.plugins] ERROR: Failed to load the processing module "class 'modules.processing.droidmon.Droidmon":
> Traceback (most recent call last):
>   File "/data/cuckoo/lib/cuckoo/core/plugins.py", line 162, in process
>     current = module(self.results)
> TypeError: **init**() takes exactly 1 argument (2 given)

also there is some diff in the http signatures, didn’t had time to check it, but i think it is minor.

also the http report and integration with web-ui is a little different
