### ISSUE TITLE
Failure in AnalysisManager.run: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by josemigueljm** [brad-accuvant/cuckoo-modified#241]
Hi ,

I have this error when generating the report module for a doc file :

/opt/cuckoo/conf# 2015-10-25 11:03:33,767 [lib.cuckoo.core.guest] INFO: win7: analysis completed successfully
2015-10-25 11:03:52,465 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label win7 to path /opt/cuckoo-modified/storage/analyses/9/memory.dmp
2015-10-25 11:04:21,878 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/opt/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 429, in run
    self.process_results()
  File "/opt/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 372, in process_results
    RunSignatures(task=self.task.to_dict(), results=results).run()
  File "/opt/cuckoo-modified/lib/cuckoo/core/plugins.py", line 560, in run
    if not family and self.results["info"]["category"] == "file" and "clamav" in self.results["target"]["file"] and self.results["target"]["file"]["clamav"].startswith("Win.Trojan."):
AttributeError: 'NoneType' object has no attribute 'startswith'

The status of analysing also hangs in "reporting". Using the latest commit from branch.

Cheers

**Comment by seanthegeek** [comment]
This is a known issue. I fixed it in PR #240. Until @brad-accuvant merges it (probably early tomorrow), you can apply that patch to fix it.

**Comment by josemigueljm** [comment]
Thanks seanthegeek
