### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by lunachy** [brad-accuvant/cuckoo-modified#265]
2015-11-21 18:31:53,470 [lib.cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver connection ('10.14.24.69', 1137)
Traceback (most recent call last):
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 223, in handle
    while self.protocol.read_next_message():
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 359, in read_next_message
    infofd = open(file_path + "_info.txt", "a")
IOError: [Errno 24] Too many open files: '/polydata/sandbox/storage/analyses/26080/files/6314531684/WAko.exe_info.txt'

**Comment by brad-sp** [comment]
That line number doesn't match up with the newest version.  Can you do an ls on the /proc/pid/fd dir of the cuckoo.py process so we can see if any file descriptors are leaking?

**Comment by lunachy** [comment]
I modified some lines, but it has no effect. It really exists some file descriptors. After I set ulimit -n 65535, this problem seems disappear.
![qq 20151124091220](https://cloud.githubusercontent.com/assets/10249962/11355271/bbc68cf2-928e-11e5-8d59-1c5cced8874d.png)
