### ISSUE TITLE
ERROR: FIXME - exception in resultserver connection

### ISSUE THREAD

**Issue by lunachy** [brad-accuvant/cuckoo-modified#270]
sample on malwr.com, md5  7a49678740820d85e6648af614889792

2015-11-27 09:43:20,997 [lib.cuckoo.core.resultserver] ERROR: FIXME - exception in resultserver connection ('10.14.24.111', 50153)
Traceback (most recent call last):
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 221, in handle
    self.negotiate_protocol()
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 191, in negotiate_protocol
    buf = self.read_newline()
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 186, in read_newline
    buf += self.read(1)
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 161, in read
    if not self.wait_sock_or_end():
  File "/polyfalcon/analysis/sandbox/lib/cuckoo/core/resultserver.py", line 154, in wait_sock_or_end
    rs, _, _ = select.select([self.request], [], [], 1)
ValueError: filedescriptor out of range in select()

I check the analysis.log and find error as follows.
2015-11-20 17:41:43,437 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 14236
2015-11-20 17:41:43,437 [root] ERROR: Traceback (most recent call last):
  File "C:\taknwgwcf\analyzer.py", line 526, in run
    handler.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Traceback (most recent call last):
  File "C:\taknwgwcf\analyzer.py", line 526, in run
    handler.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by lunachy** [comment]
consider epoll instead of select?
