### ISSUE TITLE
cPDFEOF instance has no attribute 'cntCharsAfterLastEOF'

### ISSUE THREAD

**Issue by Maxou56800** [brad-accuvant/cuckoo-modified#276]
```
[lib.cuckoo.core.scheduler] INFO: Task #x: acquired machine x (label=x)
[lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/root/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/root/cuckoo-modified/modules/processing/static.py", line 1281, in run
    static = PDF(self.file_path).run()
  File "/root/cuckoo-modified/modules/processing/static.py", line 996, in run
    results = self._parse(self.file_path)
  File "/root/cuckoo-modified/modules/processing/static.py", line 858, in _parse
    pdf_data = PDFiD(filepath, False, True)
  File "/root/cuckoo-modified/lib/cuckoo/common/pdftools/pdfid.py", line 549, in PDFiD
    attCountCharsAfterLastEOF.nodeValue = '%d' % oPDFEOF.cntCharsAfterLastEOF
AttributeError: cPDFEOF instance has no attribute 'cntCharsAfterLastEOF'
```

**Comment by KillerInstinct** [comment]
This was already fixed here:
https://github.com/spender-sandbox/cuckoo-modified/commit/1361d3ed459d8d3f6a82b89fa85a576db3887263
