### ISSUE TITLE
UTF-8 Encoding Error

### ISSUE THREAD

**Issue by jhumble** [brad-accuvant/cuckoo-modified#29]
Happened on a doc sample with MD5 436bedf80d6cd79907bac5518add3d1e (available on VT)

WARNING:lib.cuckoo.core.plugins:The reporting module "JsonDump" returned the following error: Failed to generate JSON report: 'ascii' codec can't decode byte 0x82 in position 37: ordinal not in range(128)
ERROR:lib.cuckoo.core.plugins:Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 570, in process
    current.run(self.results)
  File "/home/cuckoo/cuckoo-modified/utils/../modules/reporting/mongodb.py", line 259, in run
    self.db.analysis.save(report)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.8-py2.7-linux-x86_64.egg/pymongo/collection.py", line 285, in save
    return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.8-py2.7-linux-x86_64.egg/pymongo/collection.py", line 415, in insert
    self.uuid_subtype, client)
InvalidStringData: strings in documents must be valid UTF-8: 'F\x127a\x82sa'

**Comment by brad-sp** [comment]
I can't reproduce this -- are you running the latest version?
