### ISSUE TITLE
     Error: Analysis failed: invalid string pointer 0x03841AF000000000

### ISSUE THREAD

**Issue by Devendra007-cmd** [brad-accuvant/cuckoo-modified#305]
2023-08-28 12:13:59,000 [root] INFO: Date set to: 08-28-23, time set to: 12:13:59
2023-08-28 12:13:59,015 [root] ERROR: Traceback (most recent call last):
  File "C:\ijtvwonkye\analyzer.py", line 972, in <module>
    success = analyzer.run()
  File "C:\ijtvwonkye\analyzer.py", line 705, in run
    self.prepare()
  File "C:\ijtvwonkye\analyzer.py", line 645, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\ijtvwonkye\analyzer.py", line 588, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.UniqueProcessId))
ValueError: invalid string pointer 0x03841AF000000000
Traceback (most recent call last):
  File "C:\ijtvwonkye\analyzer.py", line 972, in <module>
    success = analyzer.run()
  File "C:\ijtvwonkye\analyzer.py", line 705, in run
    self.prepare()
  File "C:\ijtvwonkye\analyzer.py", line 645, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\ijtvwonkye\analyzer.py", line 588, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.UniqueProcessId))
ValueError: invalid string pointer 0x03841AF000000000

**Comment by Devendra007-cmd** [comment]
Please help me resolve this issue
