### ISSUE TITLE
Django Interface not rendering correctly

### ISSUE THREAD

**Issue by steve-landy** [brad-accuvant/cuckoo-modified#33]
I Just finished configuring cuckoo-modified and I tried to bring up the Django interface but it seems to not be all there. I haven't done any analysis yet but was hoping to use the interface to submit samples, etc.

This is what I'm seeing on my end just using python manage.py runserver

Any idea what might be going on? As an aside prior to getting the screen below, I was receiving a 500 error and it wasn't until I edited the settings.py file and changed DEBUG = False before I got what is shown below  

![screen shot 2015-04-16 at 9 56 39 am](https://cloud.githubusercontent.com/assets/7854165/7182333/a46528da-e41e-11e4-9168-54251fcd076e.png)

**Comment by brad-sp** [comment]
Not sure what's happening there, I'd need more info (like the output of manage.py).  I just tested it here with both Chrome and Firefox on the latest version, so it must be something in your configuration or the version of the python packages you installed.

**Comment by steve-landy** [comment]
Here is the manage.py output when I initially hit the site at http://127.0.0.1/. I needed to run python manage.py runserver --insecure because of the DEBUG = False in the settings.py file

![screen shot 2015-04-16 at 10 23 51 am](https://cloud.githubusercontent.com/assets/7854165/7182961/86a77088-e422-11e4-8acb-b301cd81a7bd.png)

**Comment by brad-sp** [comment]
You shouldn't have had to make any changes to settings.py.  The output there looks fine.  The only thing I could suggest would be trying a different version of django, since 1.8 is quite new.  I'm running with version 1.6.5 here.

**Comment by KillerInstinct** [comment]
Use web-dev tools on your browser of choice and see if the static files are 403'ing. Likely what happening is your static files aren't being served (Note the lack of the Cuckoo logo image)

EDIT: Just now saw you're using 1.8. I believe there was some security bugfixes to limit serving of static files. You may need to run ./manage.py collectstatic

**Comment by steve-landy** [comment]
Yeah, I just did a **pip install django** without specifying any specific version when installing the dependancies. 
I just checked and I'm currently running:
Name: Django
Version: 1.8
Location: /usr/local/lib/python2.7/dist-packages

I just uninstalled 1.8 and installed 1.6.5 so that my environment is similar to yours
I changed the settings.py back so that DEBUG = True (no other customizations in that file)

I'm receiving a 500 error when hitting the site using the runserver (manage.py output below)
![screen shot 2015-04-16 at 11 08 36 am](https://cloud.githubusercontent.com/assets/7854165/7184022/efcf8a18-e428-11e4-9fea-748b807c5e29.png)

**Comment by brad-sp** [comment]
Could you implement the logging mentioned here?
http://stackoverflow.com/a/10155661

That'll give us an idea of what's causing the problem.

**Comment by steve-landy** [comment]
Implemented the logging as recommended:

 Output of the initial run (Figure 1). Looks like a python module **pygal** was missing so I installed it. After installing that python module I restarted the runserver and accessed the site. The navigation menu appeared but bootstrap wasn't rendering because it couldn't locate some files (404's) (Figure 2). Those files seem to be in the right location though (Figure 3).

Any ideas, definitely getting closer :-)

### Figure 1

``` python
ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/data/cuckoo-modified/web/dashboard/views.py", line 75, in index
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 532, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 403, in _reverse_with_prefix
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 290, in _populate
    for name in pattern.reverse_dict:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/data/cuckoo-modified/web/statistics/views.py", line 13, in <module>
    from utils.health_statistics import HealthStatistics
  File "/data/cuckoo-modified/web/../utils/health_statistics.py", line 12, in <module>
    import pygal
ImportError: No module named pygal
```

### Figure 2

``` python
[16/Apr/2015 14:05:48] "GET / HTTP/1.1" 200 4463
WARNING Not Found: /static/css/style.css
WARNING Not Found: /static/css/bootstrap.min.css
[16/Apr/2015 14:05:48] "GET /static/css/style.css HTTP/1.1" 404 94
WARNING Not Found: /static/css/lightbox.css
WARNING Not Found: /static/js/jquery.js
[16/Apr/2015 14:05:48] "GET /static/css/bootstrap.min.css HTTP/1.1" 404 102
[16/Apr/2015 14:05:48] "GET /static/js/jquery.js HTTP/1.1" 404 93
[16/Apr/2015 14:05:48] "GET /static/css/lightbox.css HTTP/1.1" 404 97
```

### Figure 3

``` bash
user@servername:/data/cuckoo-modified/web/static$ ls -al
total 32
drwxrwsr-x+  8 root cuckoo 4096 Apr 14 18:54 .
drwxrwsr-x+ 11 root cuckoo 4096 Apr 14 18:54 ..
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 css
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 fonts
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 generated
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 graphic
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 img
drwxrwsr-x+  2 root cuckoo 4096 Apr 14 18:54 js
user@servername:/data/cuckoo-modified/web/static$ cd js
user@servername:/data/cuckoo-modified/web/static/js$ ls -al
total 160
drwxrwsr-x+ 2 root cuckoo  4096 Apr 14 18:54 .
drwxrwsr-x+ 8 root cuckoo  4096 Apr 14 18:54 ..
-rwxrwxr-x  1 root cuckoo  4862 Apr 14 18:54 bootstrap-fileupload.js
-rwxrwxr-x  1 root cuckoo 35452 Apr 14 18:54 bootstrap.min.js
-rwxrwxr-x  1 root cuckoo  6054 Apr 14 18:54 hexdump.js
-rwxrwxr-x  1 root cuckoo 84320 Apr 14 18:54 jquery.js
-rwxrwxr-x  1 root cuckoo 14872 Apr 14 18:54 lightbox.js
```

**Comment by steve-landy** [comment]
I got it to run finally. I ran runserver with the **--insecure** flag (i.e. **./manage.py runserver --insecure**)and everything loaded up without any problem. I then remembered I had set the **ALLOWED_HOSTS = ['*']** for testing purposes and forgot to set it back to at least **localhost**. Once I changed the **ALLOWED_HOSTS=['localhost']** and restarted the runserver (without the **--insecure** flag this time), everything loaded with no errors.

Thanks for all the help trying to pinpoint the issue. It's greatly appreciated.

Also, excellent work on the modifications the to base cuckoo project.

**Comment by brad-sp** [comment]
['*'] should have allowed all hosts (and is the default), did you have [] instead perhaps?

**Comment by steve-landy** [comment]
No I had **['*']** as my ALLOWED_HOSTS parameter. Wasn't what I expected either.
