### ISSUE TITLE
Static module failure

### ISSUE THREAD

**Issue by jcannell** [brad-accuvant/cuckoo-modified#61]
Started using this today, looks very nice. One error I'm getting:

Traceback (most recent call last):
  File "/{edited}/cuckoo-modified/lib/cuckoo/core/plugins.py", line 194, in process
    data = current.run()
  File "/{edited}/cuckoo-modified/modules/processing/static.py", line 718, in run
    static = PortableExecutable(self.file_path).run()
  File "/{edited}/cuckoo-modified/modules/processing/static.py", line 424, in run
    results["pe_overlay"] = self._get_overlay()
  File "/{edited}/cuckoo-modified/modules/processing/static.py", line 234, in _get_overlay
    off = self.pe.get_overlay_data_start_offset()
AttributeError: PE instance has no attribute 'get_overlay_data_start_offset'

Seems like this is a function call, but I don't see the function imported or defined in static.py

**Comment by brad-sp** [comment]
It's part of pefile, you must have an outdated version.  I've updated the code to give a more direct error about this.

**Comment by jcannell** [comment]
Thanks!
