### ISSUE TITLE
Failure in AnalysisManager.run

### ISSUE THREAD

**Issue by therealdreg** [brad-accuvant/cuckoo-modified#74]
I have this error after installing ./community.py -a -w -f

2015-06-04 08:14:32,276 [lib.cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2015-06-04 08:14:36,673 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): www.virustotal.com
2015-06-04 08:14:39,409 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 413, in run
    self.process_results()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 362, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/plugins.py", line 391, in run
    self._check_signature_version(sig) and (not sig.filter_analysistypes or self.results["target"]["category"] in sig.filter_analysistypes)]
  File "/home/cuckoo/cuckoo-modified/modules/signatures/andromeda_apis.py", line 33, in __init__
    if "environ" in self.results["behavior"]["processes"][0] and "SystemVolumeSerialNumber" in self.results["behavior"]["processes"][0]["environ"]:
TypeError: argument of type 'NoneType' is not iterable

**Comment by brad-sp** [comment]
Can you show me the "environ" part of your report.json for that analysis?  Just to confirm, you're also using our latest cuckoo and cuckoomon versions?

**Comment by KillerInstinct** [comment]
Do you have ram_boost turned on or off if your config?

**Comment by therealdreg** [comment]
Yes, I am using the last version (I clone the repository yesterday). I am using the cuckoomon included in cuckoomon-modified repository.

a80cfb61853b13f5c0620737e4533eac  ./analyzer/windows/dll/cuckoomon_bson.dll
9b6a68f75c6c39a5b48edbb8a6a6ea0c  ./analyzer/windows/dll/cuckoomon_x64.dll
a778dc913e8d5db379e579eb606540f1  ./analyzer/windows/dll/cuckoomon.dll
dc83b9e3c690e8bf33abc909c73f14cc  ./analyzer/windows/dll/cuckoomon_netlog.dll

Here the JSON: 
http://paste.ubuntu.com/11565021/

ram_boost = off

**Comment by KillerInstinct** [comment]
Turn ram_boost on and rerun the analysis.

**Comment by brad-sp** [comment]
Thanks, I have enough to go on now.  I should have this fixed today

**Comment by therealdreg** [comment]
BTW with ram_boost = on, works fine but I only have 8GB RAM.
