### ISSUE TITLE
Error processing

### ISSUE THREAD

**Issue by c0den** [brad-accuvant/cuckoo-modified#84]
ArmAddressSpace: No valid DTB found

2015-06-12 14:31:49,932 [Processing.Pcap] ERROR: Failed to process packet: 'type'
Traceback (most recent call last):
  File "/opt/cuckoo-modified/modules/processing/network.py", line 601, in run
    self._udp_dissect(connection, udp.data)
  File "/opt/cuckoo-modified/modules/processing/network.py", line 215, in _udp_dissect
    self._add_dns(data)
  File "/opt/cuckoo-modified/modules/processing/network.py", line 364, in _add_dns
    new_answers = set((i["type"], i["data"]) for i in query["answers"]) - self.dns_answers
  File "/opt/cuckoo-modified/modules/processing/network.py", line 364, in <genexpr>
    new_answers = set((i["type"], i["data"]) for i in query["answers"]) - self.dns_answers
KeyError: 'type'
2015-06-12 14:32:23,427 [Processing.Pcap] ERROR: Failed to process packet: 'type'
Traceback (most recent call last):
  File "/opt/cuckoo-modified/modules/processing/network.py", line 601, in run
    self._udp_dissect(connection, udp.data)
  File "/opt/cuckoo-modified/modules/processing/network.py", line 215, in _udp_dissect
    self._add_dns(data)
  File "/opt/cuckoo-modified/modules/processing/network.py", line 364, in _add_dns
    new_answers = set((i["type"], i["data"]) for i in query["answers"]) - self.dns_answers
  File "/opt/cuckoo-modified/modules/processing/network.py", line 364, in <genexpr>
    new_answers = set((i["type"], i["data"]) for i in query["answers"]) - self.dns_answers
KeyError: 'type'
2015-06-12 14:35:42,398 [modules.processing.static] ERROR: Your version of pefile is out of date.  Please update to the latest version on https://github.com/erocarrera/pefile
2015-06-12 14:35:42,623 [lib.cuckoo.common.objects] WARNING: Unable to match Yara signatures: 'error_on_warning' is an invalid keyword argument for this function
2015-06-12 14:35:42,623 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2015-06-12 14:35:56,903 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/opt/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 413, in run
    self.process_results()
  File "/opt/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 362, in process_results
    RunSignatures(task_id=self.task.id, results=results).run()
  File "/opt/cuckoo-modified/lib/cuckoo/core/plugins.py", line 391, in run
    self._check_signature_version(sig) and (not sig.filter_analysistypes or self.results["target"]["category"] in sig.filter_analysistypes)]
  File "/opt/cuckoo-modified/modules/signatures/andromeda_apis.py", line 31, in __init__
    self.sysvolserial = self.get_environ_entry(self.get_initial_process(), "SystemVolumeSerialNumber")
AttributeError: 'Andromeda_APIs' object has no attribute 'get_environ_entry'

**Comment by brad-sp** [comment]
You have a number of problems there.  Your pefile version is out of date as it mentions, and it seems your signatures are newer than your cuckoo version.

**Comment by c0den** [comment]
Let me update both and see if that fixes the problem.

**Comment by c0den** [comment]
All fixed...thanks for the help.
